name: 💡 Feature Request
description: Suggest an idea or enhancement for Nekomata.
title: "[Feature]: <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the following template to help us understand your idea.

        📚 **Contributing guidelines:** [CONTRIBUTING.md](https://github.com/Armoghans-Organization/Nekomata/blob/main/CONTRIBUTING.md)

        - 🐛 **Bug reports & issues:** Use [GitHub Issues](https://github.com/Armoghans-Organization/Nekomata/issues)
        - 💡 **Feature ideas:** Open a discussion on [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)
        - 🙋‍♀️ **General questions:** Head to [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)

  - type: checkboxes
    id: issue-check
    attributes:
      label: Issue Check
      description: Please check existing issues to see if your feature request has already been raised.
      options:
        - label: I have checked existing Issues and this feature request has not been raised
          required: true

  - type: textarea
    id: related-problem
    attributes:
      label: 🧐 Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. (If applicable)
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 💡 Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: checkboxes
    id: completeness
    attributes:
      label: Completeness Check
      description: Please confirm you have included the following
      options:
        - label: I have described the feature clearly
        - label: I have explained why this would benefit Nekomata
        - label: I have checked for related feature requests

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, links, or screenshots about the feature request here. Are there existing GitHub Issues/Discussions that you feel are related?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <p align="center">──────── ⋆⋅☆⋅⋆ ────────</p>
        <p align="center">
          Made with 🐾 and ☕ by <a href="https://github.com/Armoghans-Organization">Armoghans-Organization</a>
        </p>
        <p align="center">
          By submitting this issue, you agree to follow our <a href="https://github.com/Armoghans-Organization/Nekomata/blob/main/CODE_OF_CONDUCT.md">Code of Conduct</a>.
        </p>
