name: 📚 Documentation Request
description: Suggest improvements, corrections, or additions to Nekomata's documentation.
title: "[Docs]: <short description>"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the following template to help us understand your suggestion.

        📚 **Contributing guidelines:** [CONTRIBUTING.md](https://github.com/Armoghans-Organization/Nekomata/blob/main/CONTRIBUTING.md)

        - 🐛 **Bug reports & issues:** Use [GitHub Issues](https://github.com/Armoghans-Organization/Nekomata/issues)
        - 💡 **Feature ideas:** Open a discussion on [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)
        - 🙋‍♀️ **General questions:** Head to [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)

  - type: checkboxes
    id: issue-check
    attributes:
      label: Issue Check
      description: Please check existing issues to see if your documentation request has already been raised.
      options:
        - label: I have checked existing Issues and this documentation request has not been raised
          required: true

  - type: textarea
    id: docs-area
    attributes:
      label: 📄 Area of Documentation
      description: What part of the documentation does this concern? (e.g., Readme, API docs, usage guides, etc.)
      placeholder: Ex. Installation instructions, theme configuration, etc.
    validations:
      required: true

  - type: textarea
    id: describe-request
    attributes:
      label: 📝 Describe the Documentation Request
      description: A clear and concise description of what you want to improve, correct, or add.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 🤔 Expected Improvement
      description: What would you like to see changed or added?
    validations:
      required: false

  - type: checkboxes
    id: completeness
    attributes:
      label: Completeness Check
      description: Please confirm you have included the following
      options:
        - label: I have described the documentation request clearly
        - label: I have explained why this would benefit Nekomata
        - label: I have checked for related documentation requests

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, links, or screenshots about the documentation request here. Are there existing GitHub Issues/Discussions that you feel are related?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <p align="center">──────── ⋆⋅☆⋅⋆ ────────</p>
        <p align="center">
          Made with 🐾 and ☕ by <a href="https://github.com/Armoghans-Organization">Armoghans-Organization</a>
        </p>
        <p align="center">
          By submitting this issue, you agree to follow our <a href="https://github.com/Armoghans-Organization/Nekomata/blob/main/CODE_OF_CONDUCT.md">Code of Conduct</a>.
        </p>
