name: 🙋 General Report
description: Share feedback, ask questions, or report anything not covered by other templates.
title: "[General]: <short description>"
labels: ["question", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please use this template for general feedback, questions, or reports that don't fit other categories.
        📚 **Contributing guidelines:** [CONTRIBUTING.md](https://github.com/Armoghans-Organization/Nekomata/blob/main/CONTRIBUTING.md)

        - 🐛 **Bug reports & issues:** Use [GitHub Issues](https://github.com/Armoghans-Organization/Nekomata/issues)
        - 💡 **Feature ideas:** Open a discussion on [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)
        - 🙋‍♀️ **General questions:** Head to [GitHub Discussions](https://github.com/Armoghans-Organization/Nekomata/discussions)

  - type: checkboxes
    id: issue-check
    attributes:
      label: Issue Check
      description: Please check existing issues to see if your report has already been raised.
      options:
      - label: I have checked existing Issues and this report has not been raised
        required: true

  - type: textarea
    id: describe-report
    attributes:
      label: 📝 Describe Your Report
      description: A clear and concise description of your feedback, question, or report.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 🤔 What outcome do you expect?
      description: What would you like to see happen as a result of this report?
    validations:
      required: false

  - type: checkboxes
    id: completeness
    attributes:
      label: Completeness Check
      description: Please confirm you have included the following
      options:
        - label: I have described my report clearly
        - label: I have checked for related reports

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, links, or screenshots about your report here. Are there existing GitHub Issues/Discussions that you feel are related?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <p align="center">──────── ⋆⋅☆⋅⋆ ────────</p>
        <p align="center">
          Made with 🐾 and ☕ by <a href="https://github.com/Armoghans-Organization">Armoghans-Organization</a>
        </p>
        <p align="center">
          By submitting this issue, you agree to follow our <a href="https://github.com/Armoghans-Organization/Nekomata/blob/main/CODE_OF_CONDUCT.md">Code of Conduct</a>.
        </p>
